# Generated by Django 6.0.1 on 2026-01-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва камери')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Розташування')),
                ('stream_url', models.CharField(max_length=255, verbose_name='Потік (IP/URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='DetectedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(max_length=20, verbose_name='Розпізнаний номер')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/', verbose_name='Фото фіксації')),
                ('confidence', models.FloatField(verbose_name='Впевненість AI')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час події')),
                ('is_recognized_employee', models.BooleanField(default=False, verbose_name='Свій/Чужий')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.camera', verbose_name='Камера')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(max_length=20, unique=True, verbose_name='Номер авто')),
                ('brand_model', models.CharField(blank=True, max_length=100, verbose_name='Марка/Модель')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='recognition.employee', verbose_name='Власник')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Дозвіл')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дійсний до')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recognition.vehicle', verbose_name='Автомобіль')),
            ],
        ),
    ]
