# Generated by Django 6.0.1 on 2026-02-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedplate',
            name='is_recognized_employee',
        ),
        migrations.AddField(
            model_name='detectedplate',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.vehicle', verbose_name='Розпізнане авто'),
        ),
    ]
