# Generated by Django 6.0.1 on 2026-02-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_remove_detectedplate_is_recognized_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectedplate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Розпізнаний номер', 'verbose_name_plural': 'Розпізнані номери'},
        ),
        migrations.AlterField(
            model_name='detectedplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/', verbose_name='Фото фіксації'),
        ),
        migrations.AlterField(
            model_name='detectedplate',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='recognition.vehicle', verbose_name='Розпізнане авто'),
        ),
    ]
