# Generated by Django 6.0.1 on 2026-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_alter_detectedplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(max_length=20, unique=True, verbose_name='Номер у чорному списку')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Чорний список',
                'verbose_name_plural': 'Чорний список',
            },
        ),
    ]
