# Generated by Django 6.0.1 on 2026-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
