# Generated by Django 6.0.1 on 2026-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_vehicle_created_by_vehicle_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_first_name',
            field=models.CharField(default='Гість', max_length=50, verbose_name="Ім'я власника"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_last_name',
            field=models.CharField(default='Невідомо', max_length=50, verbose_name='Прізвище власника'),
        ),
    ]
