# Generated by Django 5.2.6 on 2026-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0010_userprofile_free_recognitions_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дійсний до'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='plan',
            field=models.CharField(choices=[('1_month', '1 місяць'), ('3_months', '3 місяці'), ('1_year', '1 рік')], default='1_month', max_length=20, verbose_name='Тарифний план'),
        ),
    ]
