# Generated by Django 6.0.1 on 2026-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0014_parkingsession_systemconfig_alter_accesspermit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='plate_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер авто (для гостьового пропуску)'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('api_key', 'API-ключ'), ('guest_pass', 'Гостьовий пропуск')], default='api_key', max_length=20, verbose_name='Тип транзакції'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.CharField(blank=True, choices=[('1_month', '1 місяць'), ('3_months', '3 місяці'), ('1_year', '1 рік')], default='1_month', max_length=20, verbose_name='Тарифний план'),
        ),
    ]
